### PR TITLE
Installing additional packages

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview 

This PR adds additional packages that seems to be missing. See https://github.com/ioos/BioData-Training-Workshop/issues/19#issuecomment-363228874

### CODE REVIEW

**Comment by emiliom** [comment]
Great, thank you! Merging.

**Comment by emiliom** [comment]
Or rather, will wait for the CI's to complete ... Actually, how come there's only AppVeyor, and no TravisCI?

**Comment by emiliom** [comment]
> Or rather, will wait for the CI's to complete ... Actually, how come there's only AppVeyor, and no TravisCI?

AppVeyor is still not done. 

Do you want me to merge, do we wait, or do you want to merge yourself?

**Comment by lsetiawan** [comment]
> AppVeyor is still not done.

It doesn't look like it started!

I can merge. Thanks.

**Pull request merged**
