### PR TITLE
OBIS QA/QC and visualisation training material

### PR DESCRIPTION
**Pull request by samuelbosch**

### CODE REVIEW

**Comment by lsetiawan** [comment]
Thanks @samuelbosch

**Comment by emiliom** [comment]
Thanks @samuelbosch ! Let's chat briefly about this during the break or lunch, before we merge. @bbest and @albenson-usgs, hopefully you can join us?

**Comment by lsetiawan** [comment]
Oops. I already merged...

**Comment by emiliom** [comment]
> Oops. I already merged...

@lsetiawan Can you undo the PR or remove that new directory? @samuelbosch and I talked. He will resubmit a PR with a tweaked version of that directory, but it'll go as a top-level directory. He will also create and submit R notebooks into the `rcode` directory

**Comment by lsetiawan** [comment]
Merge reversed. Done. Thanks.

**Comment by emiliom** [comment]
Thanks.

**Pull request merged**
