### PR TITLE
Add binder link

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/ioos/BioData-Training-Workshop/issues/30

### CODE REVIEW

**Comment by lsetiawan** [comment]
Seems like it's not using the Dockerfile.

**Comment by ocefpaf** [comment]
Do you want it to use the Dockerfile? All the notebooks run fine with the env file.

We would need to move the dockerfile to the root directory and maybe move the env file to another place. I'm not sure how binder order the resources and/or if we can just point to another directory.

**Comment by lsetiawan** [comment]
I guess we don't need to use the Dockerfile, if all the notebooks ran. We don't really have any full R demos.

**Comment by lsetiawan** [comment]
To use the docker file, I would need to put the file the root directory or on the notebooks directory.

**Comment by ocefpaf** [comment]
> I guess we don't need to to run the notebooks.

The point of creating the adding the binder link is so people can run the notebooks.

> We don't really have any full R demos.

Actually we do have 2 and they run just fine.

PS: the only limitation is to  start an RStudio session from the menu but I'll jupyter folks on that later.

**Comment by emiliom** [comment]
>> I guess we don't need to to run the notebooks.
>
> The point of creating the adding the binder link is so people can run the notebooks.

Indeed.  At least *Jupyter* notebooks.

>> We don't really have any full R demos.
>
> Actually we do have 2 and they run just fine.

Yup. Again, *Jupyter* R notebooks.

> PS: the only limitation is to start an RStudio session from the menu but I'll jupyter folks on that later.

Not a high priority. Setting up binder to run Jupyter notebooks (both Python and R), that's a pretty darn useful feature already.

Thanks @ocefpaf!

**Comment by emiliom** [comment]
I've looked at the changes in this PR, and they seem straightforward to me. I'll merge.

**Pull request merged**
