### PR TITLE
Intro to ERDDAPy

### PR DESCRIPTION
**Pull request by ocefpaf**
@lsetiawan can you take a look and merge?

### CODE REVIEW

**Comment by lsetiawan** [comment]
Look really cool! Unfortunately, I've never used `Erddapy`. I think @emiliom has, so he can probably do a more thorough review. Thanks.

**Comment by ocefpaf** [comment]
The review is if I put it in the right place  :-)

No one has used erddapy yet, it is brand new ; -p

**Comment by lsetiawan** [comment]
> The review is if I put it in the right place :-) No one has used erddapy yet, it is brand new ; -p

Oh okay haha. In that case, you're good to go 😄

**Comment by ocefpaf** [comment]
Thanks!

**Pull request merged**
